// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/users/service.proto

/*
Package users is a generated protocol buffer package.

It is generated from these files:
	rpc/users/service.proto

It has these top-level messages:
	RegisterReq
	RegisterResp
	LoginReq
	LoginResp
	UserReq
	UserResp
	CurrentUserReq
	CurrentUserResp
	User
	Session
	PrivateUser
*/
package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResp struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *RegisterResp) Reset()                    { *m = RegisterResp{} }
func (m *RegisterResp) String() string            { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()               {}
func (*RegisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *LoginResp) Reset()                    { *m = LoginResp{} }
func (m *LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()               {}
func (*LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginResp) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type UserReq struct {
	Session  *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *UserReq) Reset()                    { *m = UserReq{} }
func (m *UserReq) String() string            { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()               {}
func (*UserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserReq) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResp struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserResp) Reset()                    { *m = UserResp{} }
func (m *UserResp) String() string            { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()               {}
func (*UserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CurrentUserReq struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *CurrentUserReq) Reset()                    { *m = CurrentUserReq{} }
func (m *CurrentUserReq) String() string            { return proto.CompactTextString(m) }
func (*CurrentUserReq) ProtoMessage()               {}
func (*CurrentUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CurrentUserReq) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type CurrentUserResp struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CurrentUserResp) Reset()                    { *m = CurrentUserResp{} }
func (m *CurrentUserResp) String() string            { return proto.CompactTextString(m) }
func (*CurrentUserResp) ProtoMessage()               {}
func (*CurrentUserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CurrentUserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// User is the public user message
type User struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Session struct {
	Token    string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// PrivateUser is the message that is stored in the DB
type PrivateUser struct {
	Username       string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	PasswordSha256 []byte `protobuf:"bytes,2,opt,name=passwordSha256,proto3" json:"passwordSha256,omitempty"`
}

func (m *PrivateUser) Reset()                    { *m = PrivateUser{} }
func (m *PrivateUser) String() string            { return proto.CompactTextString(m) }
func (*PrivateUser) ProtoMessage()               {}
func (*PrivateUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PrivateUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PrivateUser) GetPasswordSha256() []byte {
	if m != nil {
		return m.PasswordSha256
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "ericmoritz.users.users.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "ericmoritz.users.users.RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "ericmoritz.users.users.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "ericmoritz.users.users.LoginResp")
	proto.RegisterType((*UserReq)(nil), "ericmoritz.users.users.UserReq")
	proto.RegisterType((*UserResp)(nil), "ericmoritz.users.users.UserResp")
	proto.RegisterType((*CurrentUserReq)(nil), "ericmoritz.users.users.CurrentUserReq")
	proto.RegisterType((*CurrentUserResp)(nil), "ericmoritz.users.users.CurrentUserResp")
	proto.RegisterType((*User)(nil), "ericmoritz.users.users.User")
	proto.RegisterType((*Session)(nil), "ericmoritz.users.users.Session")
	proto.RegisterType((*PrivateUser)(nil), "ericmoritz.users.users.PrivateUser")
}

func init() { proto.RegisterFile("rpc/users/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0xa6, 0xa5, 0x79, 0x49, 0x27, 0xa5, 0x0f, 0x96, 0xc7, 0x7b, 0x25, 0x3c, 0x68, 0x5d, 0xa5,
	0x7a, 0x4a, 0xa5, 0xa2, 0x20, 0x7a, 0x90, 0x16, 0x05, 0xb1, 0x07, 0x4d, 0xe9, 0xc5, 0x83, 0x18,
	0xeb, 0x50, 0x83, 0x34, 0xd9, 0xee, 0xa4, 0x15, 0xfc, 0xa3, 0xfe, 0x1d, 0xc9, 0x26, 0xd1, 0x46,
	0x4c, 0x2a, 0xed, 0x25, 0x30, 0x3b, 0xdf, 0x7e, 0xf3, 0xcd, 0xcc, 0x97, 0x85, 0x7f, 0x52, 0x8c,
	0x3b, 0x73, 0x42, 0x49, 0x1d, 0x42, 0xb9, 0xf0, 0xc6, 0x68, 0x0b, 0x19, 0x84, 0x01, 0xfb, 0x8b,
	0xd2, 0x1b, 0x4f, 0x03, 0xe9, 0x85, 0xaf, 0xb6, 0xca, 0xc7, 0x5f, 0x7e, 0x0e, 0xa6, 0x83, 0x13,
	0x8f, 0x42, 0x94, 0x0e, 0xce, 0x98, 0x05, 0x46, 0x74, 0xee, 0xbb, 0x53, 0x6c, 0x94, 0x5a, 0xa5,
	0xbd, 0xaa, 0xf3, 0x11, 0x47, 0x39, 0xe1, 0x12, 0xbd, 0x04, 0xf2, 0xb1, 0x51, 0x8e, 0x73, 0x69,
	0xcc, 0xcf, 0xa0, 0xf6, 0x49, 0x43, 0x82, 0xed, 0x43, 0x25, 0xba, 0xa7, 0x38, 0xcc, 0xee, 0x7f,
	0xfb, 0xfb, 0xea, 0xf6, 0x88, 0x50, 0x3a, 0x0a, 0xc9, 0x7b, 0x60, 0x0c, 0x82, 0x89, 0xe7, 0x6f,
	0xa2, 0xe2, 0x02, 0xaa, 0x09, 0x07, 0x09, 0x76, 0x0c, 0x3a, 0x21, 0x91, 0x17, 0xf8, 0x89, 0x8a,
	0x66, 0x9e, 0x8a, 0x61, 0x0c, 0x73, 0x52, 0x3c, 0xbf, 0x07, 0x5d, 0x29, 0xc3, 0xd9, 0x06, 0x2c,
	0x99, 0x2e, 0xca, 0xd9, 0x2e, 0xf8, 0x29, 0x18, 0x71, 0x85, 0xb5, 0x66, 0x75, 0x05, 0xf5, 0xfe,
	0x5c, 0x4a, 0xf4, 0xc3, 0xcd, 0x65, 0xf2, 0x3e, 0xfc, 0xce, 0x90, 0xad, 0xa5, 0x88, 0x43, 0x25,
	0x8a, 0x8a, 0x36, 0xc7, 0x4f, 0x40, 0x4f, 0x8a, 0xb3, 0x3f, 0xa0, 0x85, 0xc1, 0x33, 0xfa, 0x09,
	0x26, 0x0e, 0x0a, 0x07, 0x76, 0x03, 0xe6, 0xb5, 0xf4, 0x16, 0x6e, 0x88, 0xab, 0xea, 0xb0, 0x36,
	0xd4, 0x53, 0x47, 0x0c, 0x9f, 0xdc, 0xee, 0xe1, 0x91, 0x22, 0xab, 0x39, 0x5f, 0x4e, 0xbb, 0x6f,
	0x65, 0xd0, 0x22, 0x32, 0x62, 0x23, 0x30, 0x52, 0xf7, 0xb2, 0xed, 0xbc, 0x6e, 0x97, 0x7e, 0x13,
	0x6b, 0x67, 0x35, 0x88, 0x04, 0x1b, 0x80, 0xa6, 0xec, 0xc8, 0x5a, 0x79, 0xf0, 0xd4, 0xf1, 0xd6,
	0xd6, 0x0a, 0x04, 0x09, 0x76, 0x99, 0x8c, 0xb8, 0x59, 0xb8, 0x0e, 0x9c, 0x59, 0xad, 0x62, 0x00,
	0x09, 0x76, 0x07, 0xe6, 0xd2, 0xca, 0x59, 0x3b, 0xef, 0x42, 0xd6, 0x64, 0xd6, 0xee, 0x8f, 0x70,
	0x24, 0x7a, 0xfa, 0xad, 0xa6, 0x12, 0x0f, 0xbf, 0xd4, 0xe3, 0x73, 0xf0, 0x1e, 0x00, 0x00, 0xff,
	0xff, 0xd6, 0xc2, 0x50, 0x66, 0x97, 0x04, 0x00, 0x00,
}
